lang: de
license: "CC BY"
repo-url: https://asdf.de
project:
  type: book
  preview:
    port: 7206
    browser: false

book:
  page-footer: 
    center: 'Copyright 2022, Axel Dürkop. Dieses Werk ist lizenziert unter einer <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Namensnennung - Weitergabe unter gleichen Bedingungen 4.0 International Lizenz</a>.</p>'
  title: "Machine Learning mit Python"
  subtitle: "Einführung und Grundlagen"
  author: "Axel Dürkop"
  date: 10.13.2022
  chapters:
    - index.qmd
    - part: introduction/index.qmd
      chapters:
        - introduction/jupyter-usage.qmd
    - part: preparation/index.qmd
      chapters:
        - preparation/numpy.qmd
        - preparation/matplotlib.ipynb
        - preparation/pandas.ipynb
    - part: machine-learning/index.qmd
      chapters:
        - machine-learning/preprocessing.ipynb
        - machine-learning/linear-regression.ipynb
        - machine-learning/multiple-linear-regression.ipynb
        - machine-learning/logistic-regression.ipynb
        - machine-learning/kaufabsicht.ipynb
    - references.qmd
  appendices:
    - appendices/offene-fragen.ipynb
    - appendices/hedgedoc.md
bibliography: refs.bib

format:
  html:
    html-math-method: mathjax
    theme: light
    fontsize: 1.1em
    linestretch: 1.7
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt
