lang: de
license: "CC BY"
repo-url: https://asdf.de
project:
  type: book
  preview:
    port: 7206
    browser: false

book:
  title: "Machine Learning mit Python"
  subtitle: "Einführung und Grundlagen"
  author: "Axel Dürkop"
  date: 10.13.2022
  chapters:
    - index.qmd
    - part: introduction/index.qmd
      chapters:
        - introduction/jupyter-usage.qmd
    - part: preparation/index.qmd
      chapters:
        - preparation/numpy.ipynb
        - preparation/matplotlib.ipynb
        - preparation/pandas.ipynb
    - part: machine-learning/index.qmd
      chapters:
        - machine-learning/preprocessing.ipynb
        - machine-learning/linear-regression.ipynb
        - machine-learning/multiple-linear-regression.ipynb
        - machine-learning/logistic-regression.ipynb
    # - part: projects/index.qmd
    #   chapters:
    #     - projects/eierml.qmd
    - references.qmd
  # appendices:
  #   - appendices/installation.qmd
  #   - appendices/further.qmd
bibliography: refs.bib

format:
  html:
    html-math-method: mathjax
    theme: light
    fontsize: 1.1em
    linestretch: 1.7
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt
